# Generated by Django 4.2.11 on 2024-03-07 08:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=500)),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Contact Phone')),
                ('web', models.URLField(blank=True, verbose_name='Website Address')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('owner', models.IntegerField(default=1, verbose_name='Venue Owner')),
                ('venue_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
    ]
